//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SITE.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IBD")]
    public interface IBD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ConectarBD", ReplyAction="http://tempuri.org/IBD/ConectarBDResponse")]
        bool ConectarBD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ConectarBD", ReplyAction="http://tempuri.org/IBD/ConectarBDResponse")]
        System.Threading.Tasks.Task<bool> ConectarBDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/SUMAR", ReplyAction="http://tempuri.org/IBD/SUMARResponse")]
        int SUMAR(int Valor_1, int Valor_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/SUMAR", ReplyAction="http://tempuri.org/IBD/SUMARResponse")]
        System.Threading.Tasks.Task<int> SUMARAsync(int Valor_1, int Valor_2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBDChannel : Proyecto_SITE.Service.IBD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDClient : System.ServiceModel.ClientBase<Proyecto_SITE.Service.IBD>, Proyecto_SITE.Service.IBD {
        
        public BDClient() {
        }
        
        public BDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ConectarBD() {
            return base.Channel.ConectarBD();
        }
        
        public System.Threading.Tasks.Task<bool> ConectarBDAsync() {
            return base.Channel.ConectarBDAsync();
        }
        
        public int SUMAR(int Valor_1, int Valor_2) {
            return base.Channel.SUMAR(Valor_1, Valor_2);
        }
        
        public System.Threading.Tasks.Task<int> SUMARAsync(int Valor_1, int Valor_2) {
            return base.Channel.SUMARAsync(Valor_1, Valor_2);
        }
    }
}
